//
//  ClipboardManager.swift
//  boringNotch
//
//  Watches the system pasteboard and keeps a short in-memory history
//  (text, images, files). Nothing is written to disk.
//

import AppKit
import Combine
import Defaults

struct ClipboardItem: Identifiable, Equatable {
    enum Content: Equatable {
        case text(String)
        case image(NSImage, Data)   // Data = TIFF, used for equality and re-copying
        case files([URL])

        static func == (lhs: Content, rhs: Content) -> Bool {
            switch (lhs, rhs) {
            case let (.text(a), .text(b)): return a == b
            case let (.image(_, a), .image(_, b)): return a == b
            case let (.files(a), .files(b)): return a == b
            default: return false
            }
        }
    }

    let id = UUID()
    let content: Content
    let date: Date
    let sourceApp: NSRunningApplication?

    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool { lhs.id == rhs.id }
}

@MainActor
final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var pinnedIDs: Set<UUID> = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Password managers mark secrets with these types (nspasteboard.org) — never record them.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Reading

    private func poll() {
        guard Defaults[.showClipboardTab] else { return }
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        guard let content = readContent() else { return }

        // Same content copied again → move it to the top instead of duplicating.
        if let existing = items.firstIndex(where: { $0.content == content }) {
            items.remove(at: existing)
        }
        items.insert(ClipboardItem(content: content, date: Date(), sourceApp: NSWorkspace.shared.frontmostApplication), at: 0)
        trim()
    }

    private func readContent() -> ClipboardItem.Content? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            return .files(urls)
        }
        if let string = pasteboard.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(string)
        }
        if let image = NSImage(pasteboard: pasteboard), let tiff = image.tiffRepresentation {
            return .image(image, tiff)
        }
        return nil
    }

    private func trim() {
        let limit = max(5, Defaults[.clipboardHistoryLimit])
        // Pinned items never count against the limit and are never dropped.
        var unpinned = 0
        items = items.filter { item in
            if pinnedIDs.contains(item.id) { return true }
            unpinned += 1
            return unpinned <= limit
        }
    }

    // MARK: - Actions

    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.content {
        case .text(let string):
            pasteboard.setString(string, forType: .string)
        case .image(_, let tiff):
            pasteboard.setData(tiff, forType: .tiff)
        case .files(let urls):
            pasteboard.writeObjects(urls as [NSURL])
        }
        // Our own write bumps changeCount — skip it so the item isn't re-added, just move it up.
        lastChangeCount = pasteboard.changeCount
        if let index = items.firstIndex(of: item) {
            items.remove(at: index)
            items.insert(item, at: 0)
        }
    }

    func togglePin(_ item: ClipboardItem) {
        if pinnedIDs.contains(item.id) { pinnedIDs.remove(item.id) } else { pinnedIDs.insert(item.id) }
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        pinnedIDs.remove(item.id)
    }

    func clearUnpinned() {
        items.removeAll { !pinnedIDs.contains($0.id) }
    }
}
