"""Add Russian translations to boringNotch/Localizable.xcstrings.

Run from the repo root:  python3 scripts/add_ru_localization.py
Keys that are only format specifiers, URLs or brand names are left untranslated
(they fall back to the source string).
"""
import json
import pathlib

CATALOG = pathlib.Path("boringNotch/Localizable.xcstrings")

RU = {
    "'Now Playing' was the only option on previous versions and works with all media apps.":
        "«Сейчас играет» был единственным вариантом в прошлых версиях и работает со всеми медиаприложениями.",
    "%.0f seconds": "%.0f с",
    "%.1fs": "%.1f с",
    "• Bug fixes": "• Исправления ошибок",
    "• Improved performance": "• Улучшена производительность",
    "• New feature 1": "• Новая функция 1",
    "About": "О программе",
    "Accent color": "Цвет акцента",
    "Access Denied": "Доступ запрещён",
    "Accessibility access is required to replace the system HUD.":
        "Чтобы заменить системный HUD, нужен доступ к Универсальному доступу.",
    "Add": "Добавить",
    "Add manually": "Добавить вручную",
    "Add new visualizer": "Добавить визуализатор",
    "Additional features": "Дополнительные функции",
    "Advanced": "Дополнительно",
    "All-day": "Весь день",
    "Allow Access": "Разрешить доступ",
    "Always show full event titles": "Всегда показывать полные названия событий",
    "Always show tabs": "Всегда показывать вкладки",
    "App icon": "Значок приложения",
    "Appearance": "Внешний вид",
    "Auto-scroll to next event": "Прокручивать к следующему событию",
    "Automatically check for updates": "Автоматически проверять обновления",
    "Automatically download updates": "Автоматически загружать обновления",
    "Automatically switch displays": "Автоматически переключать дисплеи",
    "Battery": "Аккумулятор",
    "Battery Information": "Сведения об аккумуляторе",
    "Battery Settings": "Настройки аккумулятора",
    "Battery Status": "Состояние аккумулятора",
    "Boost your productivity with Clipboard Manager": "Работайте продуктивнее с менеджером буфера обмена",
    "Calendar": "Календарь",
    "Calendar access is denied. Please enable it in System Settings.":
        "Нет доступа к календарю. Разрешите его в Системных настройках.",
    "Calendars": "Календари",
    "Cancel": "Отменить",
    "Change media with horizontal gestures": "Переключать треки горизонтальными жестами",
    "Charging": "Заряжается",
    "Charging on Hold: Desktop Mode": "Зарядка приостановлена: режим настольного ПК",
    "Check for Updates…": "Проверить обновления…",
    "Choose a Music Source": "Выберите источник музыки",
    "Choose any color": "Выберите любой цвет",
    "Choose between your system accent color or customize it with your own selection.":
        "Используйте системный цвет акцента или выберите свой.",
    "Choose which service to use when sharing files from the shelf. Click the shelf button to select files, or drag files onto it to share immediately.":
        "Выберите сервис для отправки файлов с полки. Нажмите кнопку полки, чтобы выбрать файлы, или перетащите их на неё, чтобы сразу поделиться.",
    "Circle": "Круг",
    "Clear slot": "Очистить ячейку",
    "Close": "Закрыть",
    "Close gesture": "Жест закрытия",
    "Closed Notch": "Закрытая «чёлка»",
    "Color Presets": "Готовые цвета",
    "Colored spectrogram": "Цветная спектрограмма",
    "Coming soon": "Скоро",
    "Continue": "Продолжить",
    "Copy items on drag": "Копировать объекты при перетаскивании",
    "Corner radius scaling": "Масштабировать радиус углов",
    "Currently selected: %@": "Сейчас выбрано: %@",
    "Custom": "Свой",
    "Custom height": "Своя высота",
    "Custom music live activity animation": "Своя анимация музыкальной активности",
    "Custom notch size - %.0f": "Свой размер «чёлки» — %.0f",
    "Custom vizualizers (Lottie)": "Свои визуализаторы (Lottie)",
    "Customize in Settings": "Настроить в параметрах",
    "Customize which controls appear in the music player. Volume expands when active.":
        "Выберите, какие кнопки показывать в плеере. Громкость раскрывается при использовании.",
    "Default": "По умолчанию",
    "Description": "Описание",
    "Disable": "Выключить",
    "Disabled": "Выключено",
    "Download": "Загрузить",
    "Downloads": "Загрузки",
    "Drag a control onto a slot": "Перетащите кнопку в ячейку",
    "Drag items in the preview to reorder or drop from the palette":
        "Перетаскивайте элементы в превью, чтобы изменить порядок, или добавляйте из палитры",
    "Drop files here": "Перетащите файлы сюда",
    "Easily copy, store, and manage your most-used content. Upgrade now for advanced features like multi-item storage and quick access!":
        "Копируйте, храните и управляйте нужным контентом. Обновитесь, чтобы получить хранение нескольких элементов и быстрый доступ!",
    "Edit layout": "Изменить раскладку",
    "Enable blur effect behind album art": "Размытие за обложкой альбома",
    "Enable boring mirror": "Включить зеркало",
    "Enable colored spectrograms": "Включить цветные спектрограммы",
    "Enable gestures": "Включить жесты",
    "Enable glowing effect": "Включить свечение",
    "Enable haptic feedback": "Включить тактильный отклик",
    "Enable shelf": "Включить полку",
    "Enable window shadow": "Тень окна",
    "Enhance your experience with HUDs": "Улучшите работу с HUD",
    "Enjoy your free time!": "Наслаждайтесь свободным временем!",
    "Expanded drag detection area": "Расширенная зона перетаскивания",
    "Extend hover area": "Расширить зону наведения",
    "Extensions": "Расширения",
    "Files dropped on the shelf will be shared via this service":
        "Файлы, перетащенные на полку, будут отправлены через этот сервис",
    "Finish": "Готово",
    "Full screen behavior": "Поведение в полноэкранном режиме",
    "General": "Основные",
    "Gesture control": "Управление жестами",
    "Gesture sensitivity": "Чувствительность жестов",
    "Get started": "Начать",
    "Got it!": "Понятно!",
    "Gradient": "Градиент",
    "Hide all-day events": "Скрывать события на весь день",
    "Hide completed reminders": "Скрывать выполненные напоминания",
    "Hide for all apps": "Скрывать для всех приложений",
    "Hide for media app only": "Скрывать только для медиаприложения",
    "Hide from screen recording": "Скрывать при записи экрана",
    "Hide title bar": "Скрывать заголовок окна",
    "Hierarchical": "Иерархический",
    "High": "Высокая",
    "Hover delay": "Задержка наведения",
    "HUD style": "Стиль HUD",
    "HUDs": "HUD",
    "In progress": "В процессе",
    "Inline": "Встроенный",
    "Installed extensions": "Установленные расширения",
    "Layout Preview": "Превью раскладки",
    "Lottie JSON URL": "URL файла Lottie JSON",
    "Low": "Низкая",
    "Low Power Mode": "Режим энергосбережения",
    "Made with 🫶🏻 by not so boring not.people": "Сделано с 🫶🏻 not so boring not.people",
    "Mark as complete": "Отметить как выполненное",
    "Mark as incomplete": "Отметить как невыполненное",
    "Match menu bar height": "Как высота строки меню",
    "Match menubar height": "Как высота строки меню",
    "Match real notch height": "Как реальная высота «чёлки»",
    "Max Capacity: %lld%%": "Максимальная ёмкость: %lld%%",
    "Media": "Медиа",
    "Media controls": "Управление медиа",
    "Media inactivity timeout": "Тайм-аут бездействия медиа",
    "Media playback live activity": "Активность воспроизведения",
    "Media Source": "Источник медиа",
    "Medium": "Средняя",
    "Mic %@": "Микрофон %@",
    "Mirror": "Зеркало",
    "Mirror shape": "Форма зеркала",
    "More": "Ещё",
    "Music Source": "Источник музыки",
    "muted": "выключен",
    "Muted": "Выключен",
    "Name": "Название",
    "Never hide": "Никогда не скрывать",
    "No custom animation available": "Нет своих анимаций",
    "No custom visualizer": "Нет своего визуализатора",
    "No events": "Нет событий",
    "No events today": "Сегодня событий нет",
    "No extension installed": "Расширения не установлены",
    "Not Now": "Не сейчас",
    "Notch behavior": "Поведение «чёлки»",
    "Notch height on non-notch displays": "Высота на дисплеях без «чёлки»",
    "Notch height on notch displays": "Высота на дисплеях с «чёлкой»",
    "Notch sizing": "Размер «чёлки»",
    "Open Calendar Settings": "Открыть настройки календаря",
    "Open Notch": "Открытая «чёлка»",
    "Open notch on hover": "Открывать «чёлку» при наведении",
    "Open Reminder Settings": "Открыть настройки напоминаний",
    "Open shelf by default if items are present": "Открывать полку, если в ней есть файлы",
    "Option key behaviour": "Поведение клавиши Option",
    "Pick a Color": "Выберите цвет",
    "Plugged In": "Подключено к сети",
    "Preferred display": "Основной дисплей",
    "Progress bar style": "Стиль индикатора",
    "Quick Share": "Быстрая отправка",
    "Quick Share Service": "Сервис быстрой отправки",
    "Quit": "Выйти",
    "Quit app": "Выйти из приложения",
    "Release name": "Название выпуска",
    "Remember last tab": "Запоминать последнюю вкладку",
    "Reminder access is denied. Please enable it in System Settings.":
        "Нет доступа к напоминаниям. Разрешите его в Системных настройках.",
    "Reminders": "Напоминания",
    "Remove from shelf after dragging": "Убирать с полки после перетаскивания",
    "Replace system HUD": "Заменить системный HUD",
    "Replaces the standard macOS volume, display brightness, and keyboard brightness HUDs with a custom design.":
        "Заменяет стандартные индикаторы громкости, яркости дисплея и подсветки клавиатуры macOS собственным дизайном.",
    "Request Accessibility": "Запросить Универсальный доступ",
    "Reset to Defaults": "Сбросить настройки",
    "Restart": "Перезапустить",
    "Restart Boring Notch": "Перезапустить Boring Notch",
    "Running": "Работает",
    "Select the music source you want to use. You can change this later in the app settings.":
        "Выберите источник музыки. Позже его можно изменить в настройках.",
    "selected": "выбрано",
    "Selected animation": "Выбранная анимация",
    "Settings": "Настройки",
    "Shelf": "Полка",
    "Shortcuts": "Сочетания клавиш",
    "Show battery indicator": "Показывать индикатор аккумулятора",
    "Show battery percentage": "Показывать заряд в процентах",
    "Show calendar": "Показывать календарь",
    "Show cool face animation while inactive": "Показывать анимацию лица в простое",
    "Show HUD in open notch": "Показывать HUD в открытой «чёлке»",
    "Show lyrics below artist name": "Показывать текст песни под исполнителем",
    "Show menu bar icon": "Показывать значок в строке меню",
    "Show music live activity": "Показывать музыкальную активность",
    "Show notch on lock screen": "Показывать «чёлку» на экране блокировки",
    "Show on all displays": "Показывать на всех дисплеях",
    "Show percentage": "Показывать проценты",
    "Show power status icons": "Показывать значки питания",
    "Show power status notifications": "Показывать уведомления о питании",
    "Show settings icon in notch": "Показывать значок настроек в «чёлке»",
    "Show sneak peek on playback changes": "Показывать подсказку при смене трека",
    "Slider color": "Цвет ползунка",
    "Sneak Peek shows the media title and artist under the notch for a few seconds.":
        "Подсказка на несколько секунд показывает под «чёлкой» название трека и исполнителя.",
    "Sneak Peek Style": "Стиль подсказки",
    "Software updates": "Обновления",
    "Speed": "Скорость",
    "Square": "Квадрат",
    "Stopped": "Остановлено",
    "Support Us": "Поддержать нас",
    "System": "Системный",
    "System features": "Системные функции",
    "Time to Full Charge: %lld min": "До полной зарядки: %lld мин",
    "Tint progress bar with accent color": "Окрашивать индикатор в цвет акцента",
    "Toggle Notch Open:": "Открыть/закрыть «чёлку»:",
    "Toggle Sneak Peek:": "Показать/скрыть подсказку:",
    "Two-finger swipe up on notch to close, two-finger swipe down on notch to open when **Open notch on hover** option is disabled":
        "Смахните двумя пальцами вверх по «чёлке», чтобы закрыть, и вниз — чтобы открыть, когда выключено **Открывать «чёлку» при наведении**",
    "Uninstall": "Удалить",
    "Unlock advanced features and improve your experience. Upgrade now for more customizations!":
        "Откройте расширенные функции. Обновитесь, чтобы получить больше настроек!",
    "unmuted": "включён",
    "Unmuted": "Включён",
    "Upgrade to Pro": "Перейти на Pro",
    "Use music visualizer spectrogram": "Спектрограмма в визуализаторе",
    "Use your macOS system accent color": "Использовать системный цвет акцента macOS",
    "Using System Accent": "Используется системный акцент",
    "Version": "Версия",
    "Version info": "Сведения о версии",
    "View on GitHub: pear-devs/pear-desktop": "Открыть на GitHub: pear-devs/pear-desktop",
    "Welcome": "Добро пожаловать",
    "What's New": "Что нового",
    "Window Appearance": "Вид окна",
    "Window Behavior": "Поведение окна",
    "You can now enjoy the app. If you want to tweak things further, you can always visit the settings.":
        "Всё готово. Если захотите что-то изменить, загляните в настройки.",
    "You're All Set!": "Всё готово!",
    "Your macOS system accent color": "Системный цвет акцента macOS",
    "YouTube Music requires this third-party app to be installed: ":
        "Для YouTube Music нужно установить стороннее приложение: ",

    # --- Custom tabs (Tasks / Clipboard / Screenshots settings) ---
    "Tasks": "Задачи",
    "Show Tasks tab": "Показывать раздел «Задачи»",
    "Server URL": "Адрес сервера",
    "Token (optional)": "Токен (необязательно)",
    "Refresh every %lld min": "Обновлять каждые %lld мин",
    "Checking…": "Проверка…",
    "Test connection": "Проверить подключение",
    "Things Cloud MCP server": "Сервер Things Cloud MCP",
    "Address of your self-hosted things-cloud-mcp endpoint. The token is sent as \"Authorization: Bearer …\" if set.":
        "Адрес вашего сервера things-cloud-mcp. Если указан токен, он отправляется как «Authorization: Bearer …».",
    "✓ Connected — %lld areas": "✓ Подключено — областей: %lld",
    "Clipboard & Screenshots": "Буфер и скриншоты",
    "Clipboard": "Буфер обмена",
    "Screenshots": "Скриншоты",
    "Show Clipboard tab and record history": "Показывать раздел «Буфер» и записывать историю",
    "Keep last %lld items": "Хранить последние %lld",
    "History lives in memory only and is cleared when the app quits. Passwords copied from password managers are skipped.":
        "История хранится только в памяти и очищается при выходе. Пароли из менеджеров паролей не сохраняются.",
    "Show Screenshots tab": "Показывать раздел «Скриншоты»",
    "No folder selected": "Папка не выбрана",
    "Choose…": "Выбрать…",
    "Show last %lld screenshots": "Показывать последние %lld",
}


def main() -> None:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = data["strings"]
    added_keys, translated = 0, 0
    for key, value in RU.items():
        entry = strings.get(key)
        if entry is None:
            entry = strings[key] = {}
            added_keys += 1
        entry.setdefault("localizations", {})["ru"] = {
            "stringUnit": {"state": "translated", "value": value}
        }
        translated += 1
    # Existing key order is kept; Xcode re-sorts the catalog itself on the next build.
    CATALOG.write_text(
        json.dumps(data, ensure_ascii=False, indent=2, separators=(",", " : ")) + "\n",
        encoding="utf-8",
    )
    print(f"ru: {translated} strings ({added_keys} new keys)")


if __name__ == "__main__":
    main()
